/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 10
#define ALIAS_COUNT 6
#define TOKEN_COUNT 4
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 13
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 7
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_LF = 2,
  sym_field = 3,
  sym_csv = 4,
  sym_row = 5,
  sym__cycle7 = 6,
  sym__remainder = 7,
  aux_sym_csv_repeat1 = 8,
  aux_sym_row_repeat1 = 9,
  alias_sym_fifth = 10,
  alias_sym_fourth = 11,
  alias_sym_second = 12,
  alias_sym_seventh = 13,
  alias_sym_sixth = 14,
  alias_sym_third = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_LF] = "\n",
  [sym_field] = "first",
  [sym_csv] = "csv",
  [sym_row] = "row",
  [sym__cycle7] = "_cycle7",
  [sym__remainder] = "_remainder",
  [aux_sym_csv_repeat1] = "csv_repeat1",
  [aux_sym_row_repeat1] = "row_repeat1",
  [alias_sym_fifth] = "fifth",
  [alias_sym_fourth] = "fourth",
  [alias_sym_second] = "second",
  [alias_sym_seventh] = "seventh",
  [alias_sym_sixth] = "sixth",
  [alias_sym_third] = "third",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LF] = anon_sym_LF,
  [sym_field] = sym_field,
  [sym_csv] = sym_csv,
  [sym_row] = sym_row,
  [sym__cycle7] = sym__cycle7,
  [sym__remainder] = sym__remainder,
  [aux_sym_csv_repeat1] = aux_sym_csv_repeat1,
  [aux_sym_row_repeat1] = aux_sym_row_repeat1,
  [alias_sym_fifth] = alias_sym_fifth,
  [alias_sym_fourth] = alias_sym_fourth,
  [alias_sym_second] = alias_sym_second,
  [alias_sym_seventh] = alias_sym_seventh,
  [alias_sym_sixth] = alias_sym_sixth,
  [alias_sym_third] = alias_sym_third,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_csv] = {
    .visible = true,
    .named = true,
  },
  [sym_row] = {
    .visible = true,
    .named = true,
  },
  [sym__cycle7] = {
    .visible = false,
    .named = true,
  },
  [sym__remainder] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_csv_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_row_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_fifth] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_fourth] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_second] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_seventh] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_sixth] = {
    .visible = true,
    .named = true,
  },
  [alias_sym_third] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_second,
  },
  [2] = {
    [2] = alias_sym_second,
    [4] = alias_sym_third,
  },
  [3] = {
    [2] = alias_sym_second,
    [4] = alias_sym_third,
    [6] = alias_sym_fourth,
  },
  [4] = {
    [2] = alias_sym_second,
    [4] = alias_sym_third,
    [6] = alias_sym_fourth,
    [8] = alias_sym_fifth,
  },
  [5] = {
    [2] = alias_sym_second,
    [4] = alias_sym_third,
    [6] = alias_sym_fourth,
    [8] = alias_sym_fifth,
    [10] = alias_sym_sixth,
  },
  [6] = {
    [2] = alias_sym_second,
    [4] = alias_sym_third,
    [6] = alias_sym_fourth,
    [8] = alias_sym_fifth,
    [10] = alias_sym_sixth,
    [12] = alias_sym_seventh,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == ',') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == ',') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_field);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_field);
      if (lookahead == '"') ADVANCE(1);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_field);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_field);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '"' &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_field);
      if (eof) ADVANCE(3);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '"') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(7);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',') ADVANCE(10);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 11},
  [8] = {.lex_state = 11},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 9},
  [23] = {.lex_state = 9},
  [24] = {.lex_state = 9},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 9},
  [27] = {.lex_state = 9},
  [28] = {.lex_state = 9},
  [29] = {.lex_state = 9},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 9},
  [36] = {.lex_state = 9},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 2},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_csv] = STATE(20),
    [sym_row] = STATE(2),
    [sym__cycle7] = STATE(17),
    [sym__remainder] = STATE(19),
    [aux_sym_csv_repeat1] = STATE(2),
    [aux_sym_row_repeat1] = STATE(4),
    [anon_sym_LF] = ACTIONS(3),
    [sym_field] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym_row] = STATE(3),
    [sym__cycle7] = STATE(17),
    [sym__remainder] = STATE(19),
    [aux_sym_csv_repeat1] = STATE(3),
    [aux_sym_row_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(7),
    [anon_sym_LF] = ACTIONS(3),
    [sym_field] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym_row] = STATE(3),
    [sym__cycle7] = STATE(17),
    [sym__remainder] = STATE(19),
    [aux_sym_csv_repeat1] = STATE(3),
    [aux_sym_row_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(9),
    [anon_sym_LF] = ACTIONS(11),
    [sym_field] = ACTIONS(14),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      sym_field,
    ACTIONS(17), 1,
      anon_sym_LF,
    STATE(5), 1,
      aux_sym_row_repeat1,
    STATE(17), 1,
      sym__cycle7,
    STATE(18), 1,
      sym__remainder,
  [16] = 4,
    ACTIONS(19), 1,
      anon_sym_LF,
    ACTIONS(21), 1,
      sym_field,
    STATE(5), 1,
      aux_sym_row_repeat1,
    STATE(17), 1,
      sym__cycle7,
  [29] = 2,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 2,
      anon_sym_LF,
      sym_field,
  [37] = 2,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 2,
      anon_sym_LF,
      sym_field,
  [45] = 2,
    ACTIONS(32), 1,
      ts_builtin_sym_end,
    ACTIONS(34), 2,
      anon_sym_LF,
      sym_field,
  [53] = 2,
    ACTIONS(36), 1,
      anon_sym_COMMA,
    ACTIONS(38), 1,
      anon_sym_LF,
  [60] = 1,
    ACTIONS(19), 2,
      anon_sym_LF,
      sym_field,
  [65] = 2,
    ACTIONS(40), 1,
      anon_sym_COMMA,
    ACTIONS(42), 1,
      anon_sym_LF,
  [72] = 2,
    ACTIONS(44), 1,
      anon_sym_COMMA,
    ACTIONS(46), 1,
      anon_sym_LF,
  [79] = 2,
    ACTIONS(48), 1,
      anon_sym_COMMA,
    ACTIONS(50), 1,
      anon_sym_LF,
  [86] = 2,
    ACTIONS(52), 1,
      anon_sym_COMMA,
    ACTIONS(54), 1,
      anon_sym_LF,
  [93] = 2,
    ACTIONS(56), 1,
      anon_sym_COMMA,
    ACTIONS(58), 1,
      anon_sym_LF,
  [100] = 2,
    ACTIONS(60), 1,
      anon_sym_COMMA,
    ACTIONS(62), 1,
      anon_sym_LF,
  [107] = 1,
    ACTIONS(64), 1,
      anon_sym_COMMA,
  [111] = 1,
    ACTIONS(66), 1,
      anon_sym_LF,
  [115] = 1,
    ACTIONS(68), 1,
      anon_sym_LF,
  [119] = 1,
    ACTIONS(70), 1,
      ts_builtin_sym_end,
  [123] = 1,
    ACTIONS(72), 1,
      anon_sym_COMMA,
  [127] = 1,
    ACTIONS(74), 1,
      sym_field,
  [131] = 1,
    ACTIONS(76), 1,
      sym_field,
  [135] = 1,
    ACTIONS(78), 1,
      sym_field,
  [139] = 1,
    ACTIONS(80), 1,
      anon_sym_COMMA,
  [143] = 1,
    ACTIONS(82), 1,
      sym_field,
  [147] = 1,
    ACTIONS(84), 1,
      sym_field,
  [151] = 1,
    ACTIONS(86), 1,
      sym_field,
  [155] = 1,
    ACTIONS(88), 1,
      sym_field,
  [159] = 1,
    ACTIONS(90), 1,
      anon_sym_COMMA,
  [163] = 1,
    ACTIONS(92), 1,
      sym_field,
  [167] = 1,
    ACTIONS(94), 1,
      anon_sym_COMMA,
  [171] = 1,
    ACTIONS(96), 1,
      anon_sym_COMMA,
  [175] = 1,
    ACTIONS(98), 1,
      sym_field,
  [179] = 1,
    ACTIONS(100), 1,
      sym_field,
  [183] = 1,
    ACTIONS(102), 1,
      sym_field,
  [187] = 1,
    ACTIONS(104), 1,
      anon_sym_COMMA,
  [191] = 1,
    ACTIONS(106), 1,
      sym_field,
  [195] = 1,
    ACTIONS(108), 1,
      anon_sym_COMMA,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 16,
  [SMALL_STATE(6)] = 29,
  [SMALL_STATE(7)] = 37,
  [SMALL_STATE(8)] = 45,
  [SMALL_STATE(9)] = 53,
  [SMALL_STATE(10)] = 60,
  [SMALL_STATE(11)] = 65,
  [SMALL_STATE(12)] = 72,
  [SMALL_STATE(13)] = 79,
  [SMALL_STATE(14)] = 86,
  [SMALL_STATE(15)] = 93,
  [SMALL_STATE(16)] = 100,
  [SMALL_STATE(17)] = 107,
  [SMALL_STATE(18)] = 111,
  [SMALL_STATE(19)] = 115,
  [SMALL_STATE(20)] = 119,
  [SMALL_STATE(21)] = 123,
  [SMALL_STATE(22)] = 127,
  [SMALL_STATE(23)] = 131,
  [SMALL_STATE(24)] = 135,
  [SMALL_STATE(25)] = 139,
  [SMALL_STATE(26)] = 143,
  [SMALL_STATE(27)] = 147,
  [SMALL_STATE(28)] = 151,
  [SMALL_STATE(29)] = 155,
  [SMALL_STATE(30)] = 159,
  [SMALL_STATE(31)] = 163,
  [SMALL_STATE(32)] = 167,
  [SMALL_STATE(33)] = 171,
  [SMALL_STATE(34)] = 175,
  [SMALL_STATE(35)] = 179,
  [SMALL_STATE(36)] = 183,
  [SMALL_STATE(37)] = 187,
  [SMALL_STATE(38)] = 191,
  [SMALL_STATE(39)] = 195,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_csv, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_csv_repeat1, 2, 0, 0),
  [11] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_csv_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [14] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_csv_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 1, 0, 0),
  [26] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 1, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 3, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 3, 0, 0),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 2, 0, 0),
  [34] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 2, 0, 0),
  [36] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 5, 0, 2),
  [40] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 3, 0, 1),
  [44] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 7, 0, 3),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__cycle7, 13, 0, 6),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 13, 0, 6),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 9, 0, 4),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__remainder, 11, 0, 5),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [70] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__cycle7, 13, 0, 6),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_csv(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "csv",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 2,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
